spring.application.name=backend
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/portfolio_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:2425779}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${SERVER_PORT:8081}

app.jwt.secret=${JWT_SECRET:ZmFrZVNlY3JldFRvQmVSZXBsYWNlZFdpdGhBbjMyQnl0ZUtleQ==}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

app.mail.enabled=${MAIL_ENABLED:true}
app.mail.to=${MAIL_TO:amarwade927@gmail.com}
app.mail.from=${MAIL_FROM:noreply@portfolio.local}

spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:amarwade927@gmail.com}
spring.mail.password=${MAIL_PASSWORD:loezhszzistlqhdt}
spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_SMTP_STARTTLS:true}

